### ISSUE TITLE
Nice Work ... __init__ empty

### ISSUE THREAD

**Issue by herdtan** [sibartel/lecroyutils#1]
__init__.py is empty

**Comment by sibartel** [comment]
That's intended and totally fine, see [here](https://docs.python.org/3/tutorial/modules.html#packages):

> The `__init__.py` files are required to make Python treat directories containing the file as packages. This prevents directories with a common name, such as `string`, unintentionally hiding valid modules that occur later on the module search path. In the simplest case, `__init__.py` can just be an empty file, but it can also execute initialization code for the package or set the `__all__` variable, described later.
